<?php
	$page_bg_color  = "#cccccc";
        $body_bg_color  = "#ffffff";
        $title_bg_color = "#3480ba";
        $hd_bg_color1   = "#3480ba";
        $hd_bg_color2   = "#cccc99";
        $data_bg_color1 = "#dddddd";
        $data_bg_color2 = "#cccc99";

        $page_txt_color  = "#000000";
        $body_txt_color  = "#ffffff";
        $title_txt_color = "#ffffff";
        $hd_txt_color1   = "#ffffff";
        $hd_txt_color2   = "#000000";
        $data_txt_color1 = "#000000";
        $data_txt_color2 = "#000000";

	$create_user = "create";
	$create_pass = "contest";
?>
