<?
#
# Copyright (C) 2002 David Whittington 
#
# See the file "COPYING" for further information about the copyright
# and warranty status of this work.
#
# arch-tag: lib/motd.inc
#

    /*
    **  motd.inc
    **
    **  This file is included in main.php and is the first thing
    **  that people will see when they log in.  A general welcome
    **  or perhaps rules could be relevant here.  Maybe just have
    **  links to other sections of the site.  Whatever you want.
    **
    **  Just edit plain HTML or add PHP code if you so desire.
    */

?>
Welcome to <?=$contest_host?>'s <?=$contest_name?>!<br><br>

This web interface is designed to allow you to keep an eye on your
standings and to view your results as the contest progresses.  Should
you have problems, please see an administrator to remedy the issue.
